languageCode = "en-us"
title = "Escape"
baseURL = "https://escape.ankyra.io/"
pygmentsCodeFences = true
pygmentsStyle = "friendly"
pygmentsOptions = ""

[params]
    gaTrackingId = ""
    escapeClientVersion = "0.25.6"
    escapeInventoryVersion = "0.16.0"


[menu]
    [[menu.ankyra]]
    identifier = "home"
    name       = "Home"
    url        = "https://www.ankyra.io/"
    weight     = 1

    [[menu.ankyra]]
    identifier = "docs"
    name       = "Docs"
    url        = "/docs/"
    weight     = 3

    [[menu.ankyra]]
    name       = "Contact"
    url        = "https://www.ankyra.io/#contact"
    weight     = 6

    [[menu.ankyra]]
    name       = "Follow us on Twitter"
    pre        = "<i class='fa fa-twitter' aria-hidden='true'></i>&nbsp;"  
    url        = "https://twitter.com/AnkyraLtd"
    weight     = 7

